// TODO:
// 1. Read the auth folder generated by baileys
const fs = require("fs");
const { transcribeAudio } = require("./spitch");
const { summarizeText } = require("./gemini");
const {default: makeWASocket, useMultiFileAuthState, downloadMediaMessage } = require("@whiskeysockets/baileys");
async function main() {
    // checks if the auth folder exists, if not, creates it
    if(!fs.existsSync("./auth")) {
        fs.mkdirSync("./auth");
    };

    // uses the multi file auth state
    // savecreds saves the credentials to the auth folder
    const { state, saveCreds } = await useMultiFileAuthState("./auth");

    // creates a new socket
    const socket = makeWASocket({
        auth: state,
        printQRInTerminal: true,
    });

    // saves the credentials to the auth folder
    socket.ev.on("creds.update", saveCreds);

    socket.ev.on("messages.upsert", async ({messages}) => {
        const msg = messages[0];
        if (!msg.message) return;

        const from = msg.key.remoteJid;
        const messageText = msg.message.conversation || msg.message.extendedTextMessage?.text || "";

        // checks if the message is a command and if it matches "/ditto"
        const isCommand = messageText.toLowerCase() === "/ditto"

        const quotedMsg = msg.message.extendedTextMessage?.contextInfo?.quotedMessage;

        const isAudioMessage = quotedMsg?.audioMessage;

        // if the message is a command and is an audio message, then it will be processed
        if (isCommand && isAudioMessage) {
            try{
                // TODO:
                // 1. Download the audio message
                const audioMessage = await downloadMediaMessage({
                    message: quotedMsg,
                }, "buffer", {}, {
                    logger: console,
                    reuploadRequest: socket.updateMediaMessage
                });

                // 2. Transcribe with spitch STT (speech to text)
                const stt = await transcribeAudio(audioMessage);
                const transcript = stt.text;

                console.log(`📃 Transcript \n ${transcript}`);

                // 3. Summarize the transcribed audio with GEMINI
                const transcriptSummary = await summarizeText(transcript);

                // 4. Send the transcription and summary to the user
                await socket.sendMessage(from, {
                    text: `Ditto ⚡️ \n *Summary:* ${transcriptSummary}\n\n *Transcription:* ${transcript}`
                }, { quoted: msg });

            } catch (error) {
                console.error(error);

                // sends a message to the user that an error 
                // occurred while processing the audio message
                await socket.sendMessage(from, {
                    text: "An error occurred while processing the audio message."
                }, { quoted: msg });
            }
        }
    });


    socket.ev.on("connection.update", (update) => {
        const {connection, lastDisconnect} = update;

        if (connection === "close") {
            console.log("Connection closed");
            
            if (lastDisconnect?.error?.output?.statusCode !== 401) {
                console.log("Reconnecting...");
                main().catch(console.error);
            }
        } else if (connection === "open") {
            console.log("Connected to WhatsApp ✅");
        }
    })

    console.log("Hello from ditto");
}

main().catch(console.error);